EMPLOYEE_DISCOUNT_IN_PERCENTAGE = 30
AFFILIATE_DISCOUNT_IN_PERCENTAGE = 10
CUSTOME_FOR_2_YRS_DISCOUNT_IN_PERCENTAGE = 5
MISC_BILL_AMNT_IN_DOLLER = 100
MISC_BILL_AMNT_DISCOUNT_IN_DOLLER = 5
GROCERY_ITEM_CODE = 'G'